# 256 colors for vim
set -g default-terminal "screen-256color"

# Start window numbering at 1
set-option -g base-index 1
set-window-option -g pane-base-index 1
set-window-option -g aggressive-resize on

# so you don't end up with window numbers like: 0 1 4 5 6
set-option -g renumber-windows on

set-option -g default-shell /bin/zsh

# remap prefix to Control + a
# set -g prefix C-a

# bind-key 'C-a C-a' to type 'C-a'
# bind-key C-a send-prefix
# unbind-key C-b

# use vi keys
setw -g mode-keys vi

# vim copy paste mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle

# set scroll history to 100,000 lines
set -g history-limit 100000

# C-l is taken over by vim style pane navigation
bind-key C-l send-keys 'C-l'

# mouse support
set -g mouse on
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
# bind-key -T copy-mode-vi send-keys copy-pipe

# prefix r: reload tmux config
bind-key r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"

# make new panes and windows use the pwd
bind-key | split-window -h -c "#{pane_current_path}"
bind-key - split-window -v -c "#{pane_current_path}"
bind-key c new-window -c "#{pane_current_path}"

# make iterm window/tab name reflect tmux session
set-option -g set-titles on
set-option -g set-titles-string '#S'
