# Here you list all the shortcuts.
#
# The shortcuts may be defined in two ways:
#
# 1. Run-or-raise form: shortcut,launch-command,[wm_class],[title]
#        * wm_class and title are optional and case sensitive
#        * if none is set, lowercased launch-command is compared with lowercased windows wm_classes and titles
#
# 2. Run only form: shortcut,calculate 
#
#
# =================
# Run or raise form
# =================
# 
#
# This line cycles any firefox window (matched by "firefox" in the window title) OR if not found, launches new firefox instance.
<Super>f,firefox-developer-edition,firefoxdeveloperedition,
# This line cycles any open gnome-terminal (matched by wm_class = Gnome-terminal on Ubuntu 17.10) OR if not found, launches new one.
# If you're using Arch, you may want to match by wm_class = gnome-terminal-server , just check yourself by Alt+F2/lg/Windows
<Super>t,gnome-terminal,gnome-terminal-server,malonso@arch
<Super>e,nautilus,org.gnome.Nautilus,


# =============
# Run only form
# =============
#
# This line will launch notify-send command.
<Super>h,notify-send Hello world




# Blank lines are allowed. Line starting with "#" means a comment.
# Now delete these shortcuts and put here yours.
# How to know wm_class? Alt+f2, lg, "windows" tab (at least on Ubuntu 17.10)
